config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'application#home'

  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope { order(id: :desc) }

  belongs_to :user
  belongs_to :parent, class_name: "Comment"
  has_many :children, class_name: "Comment", foreign_key: "parent_id", inverse_of:  :parent

  validates :message, presence: true

  private

  def self.roots
    where(parent_id: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,   presence: true

  has_many :comments

  has_attached_file :avatar,
    styles: { thumb: '150x150>' },
    default_url: "users/missing.png"
  validates_attachment :avatar,
    content_type: {content_type: /\Aimage\/.*\Z/},
    size: { in: 0..5.megabytes, message: 'Photo size too large. Please limit to 5 mbs.' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @root_comments = Comment.includes(:children).roots
  end

  def new
    @comment = Comment.new
    @parent_id = params[:parent]
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end

  def edit
    @comment = Comment.find(comment_id)
    @result = true if (current_user == @comment.user && !@comment.children.present?)
  end

  def update
    @comment = Comment.find(comment_id)
    @comment.update(comment_params)
  end

  def destroy
    @comment = Comment.find(comment_id)
    if (current_user == @comment.user && !@comment.children.present?)
      @result = true
      @comment.destroy
    end
  end

  private

  def comment_params
    data = params.require(:comment).permit(:message, :parent_id)
    data[:user_id] = current_user.id
    data
  end

  def comment_id
    params.require(:id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :avatar, :password, :password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.slim
#application-home-container
  .container
    h1 Wellcom to rails test 10

app/views/comments/_form.html.slim
li class="form-comment#{@comment.id}"
  .comments-form-container
    = simple_form_for @comment, remote: true do |f|
      = f.input :message, label: false, placeholder: 'Enter your comment here!'
      = f.hidden_field :parent_id, value: parent_id
      = f.submit 'Send', class: "btn btn-primary"

app/views/comments/_item.html.slim
li.comments-item-container id="comment_#{comment.id}"
  .comment-wrap
    - user = comment.user
    .user
      = image_tag(user.avatar.url(:thumb))
    .comment-content
      .user-name
        h4 = user.name
      span = comment.message
      .actions
        .reply.item id="reply_#{comment.id}"
          = link_to 'Reply', new_comment_path(parent: comment), class: 'reply', remote: true
        .edit.item
          = link_to 'Edit', edit_comment_path(comment), class: 'edit', remote: true
        .destroy.item
          = link_to('Delete', comment_path(comment), method: :delete, remote: true, data: { confirm: 'Are you sure you want to delete this product?'})

  ul class="comment_#{comment.id}"
    - if comment.children.present?
      = render 'comments/list', comments: comment.children

app/views/comments/_list.html.slim
- comments.each do |comment|
  = render "comments/item", comment: comment

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  BootstrapDialog.show({
    title: "Message",
    message: "<%= @comment.errors.full_messages.join('<br />').html_safe %>",
    type: BootstrapDialog.TYPE_DEFAULT
  });
<% else %>
  <% if @comment.parent.present? %>
    $("#comment_<%= @comment.parent.id %> .comment_<%= @comment.parent.id %> li.form-comment").remove();
    $("#reply_<%= @comment.parent.id %> a").removeClass('disabled');
    $("#comment_<%= @comment.parent.id %> .comment_<%= @comment.parent.id %>").prepend("<%= escape_javascript(render partial: 'comments/item', locals: { comment: @comment }) %>")
  <% else %>
    $(".comment-box > ul li.form-comment").remove()
    $(".btn-new-comment").removeClass('disabled');
    $(".comment-box > ul").prepend("<%= escape_javascript(render partial: 'comments/item', locals: { comment: @comment }) %>")
  <% end %>  
<% end %>

app/views/comments/destroy.js.erb
<% if @result.present? %>
  $("#comment_<%= @comment.id %>").remove();
<% else %>
  BootstrapDialog.show({
    title: "Message",
    message: "You can not delete this comment!",
    type: BootstrapDialog.TYPE_DEFAULT
  });
<% end %>

app/views/comments/edit.js.erb
<% if @result.present? %>
  $("#comment_<%= @comment.id %>").replaceWith("<%= escape_javascript(render partial: 'comments/form', locals: { comment: @comment, parent_id: @parent_id }) %>")
<% else %>
  BootstrapDialog.show({
    title: "Message",
    message: "You can not edit this comment!",
    type: BootstrapDialog.TYPE_DEFAULT
  });
<% end %>

app/views/comments/index.html.slim
#comment-index-container
  .container
    .action-new
      = link_to 'New Comment', new_comment_path, class: 'btn btn-primary btn-new-comment', remote: true
    .comment-box
      ul
        = render 'comments/list', comments: @root_comments

app/views/comments/new.js.erb
<% if @parent_id.present? %>
  $("#reply_<%= @parent_id %> a").addClass('disabled');
  $("#comment_<%= @parent_id %> .comment_<%= @parent_id %>").prepend("<%= escape_javascript(render partial: 'comments/form', locals: { comment: @comment, parent_id: @parent_id }) %>")
<% else %>
  $(".btn-new-comment").addClass('disabled');
  $(".comment-box > ul").prepend("<%= escape_javascript(render partial: 'comments/form', locals: { comment: @comment, parent_id: '' }) %>")
<% end %>

app/views/comments/update.js.erb
<% if @comment.errors.any? %>
  BootstrapDialog.show({
    title: "Message",
    message: "<%= @comment.errors.full_messages.join('<br />').html_safe %>",
    type: BootstrapDialog.TYPE_DEFAULT
  });
<% else %>
  $(".form-comment<%= @comment.id %>").replaceWith("<%= escape_javascript(render partial: 'comments/item', locals: { comment: @comment }) %>") 
<% end %>

app/views/layouts/_footer.html.slim
.layouts-footer-container

app/views/layouts/_head.html.slim
meta content="width=device-width, initial-scale=1" name="viewport" /
title Test-10

= stylesheet_link_tag    'application', media: 'all'
= javascript_include_tag 'application'
= csrf_meta_tags

app/views/layouts/_header.html.slim
.layouts-header-container
  = render 'layouts/menu'

app/views/layouts/_menu.html.slim
.layouts-menu-container
  nav.navbar.navbar-default
    .container-fluid
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#main-menu-wrap1" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .collapse.navbar-collapse#main-menu-wrap1
            ul.nav.navbar-nav
              li = link_to 'Home', root_path
              li = link_to 'Comments', comments_path
              - if user_signed_in?
                li = link_to 'Log Out', destroy_user_session_path, method: :delete
              - else
                li = link_to 'Sign In', new_user_session_path
                li = link_to 'Sign Up', new_user_registration_path

app/views/layouts/_message.html.slim
#system-message.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title.text-center Message
      .modal-body
        - flash.each do |type, message|
         = simple_format message
coffee:
  if $('#system-message .modal-body p').first().text() != ''
    $('#system-message').modal('show')

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/head'
  body
    header
      = render 'layouts/header'
    main
      = yield
      == yield :popup
    = render 'layouts/message'
    footer
      = render 'layouts/footer'